version: "3.8"

services:
  api_service:
    build: .
    restart: always
    ports:
      - "9090:8080"
    networks:
      - springapimysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3309/photo_app?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: erick
      SPRING_DATASOURCE_PASSWORD: Erick_1022
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - ./.m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3309:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: photo_app
      MYSQL_USER: erick
      MYSQL_PASSWORD: Erick_1022
      MYSQL_ROOT_PASSWORD: Erick_1022
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  springapimysql-net:
